/** @type {import('stylelint').Config} */

const config = {
  extends: ["stylelint-config-standard", "stylelint-config-standard-scss"],
  plugins: ["stylelint-order"],
  rules: {
    "order/order": ["custom-properties", "declarations"],
    "order/properties-order": [
      [
        "content",
        "cursor",
        "opacity",
        "visibility",
        "pointer-events",
        "user-select",

        "overflow",
        "overflow-x",
        "overflow-y",

        "position",
        "inset",
        "inset-block-start",
        "inset-block-end",
        "inset-inline-start",
        "inset-inline-end",
        "z-index",

        "display",
        "flex-direction",
        "box-sizing",
        "grid-template-columns",
        "grid-template-rows",
        "grid-column",
        "grid-row",
        "grid-area",
        "align-items",
        "align-content",
        "align-self",
        "justify-items",
        "justify-content",
        "justify-self",
        "flex",
        "flex-wrap",
        "flex-grow",
        "flex-shrink",
        "flex-basis",
        "gap",
        "row-gap",
        "column-gap",

        "margin",
        "margin-block",
        "margin-block-start",
        "margin-block-end",
        "margin-inline",
        "margin-inline-start",
        "margin-inline-end",

        "padding",
        "padding-block",
        "padding-block-start",
        "padding-block-end",
        "padding-inline",
        "padding-inline-start",
        "padding-inline-end",

        "block-size",
        "max-block-size",
        "min-block-size",
        "inline-size",
        "max-inline-size",
        "min-inline-size",
        "aspect-ratio",

        "font",
        "font-family",
        "font-size",
        "font-weight",
        "font-style",
        "color",
        "letter-spacing",
        "line-height",
        "text-align",
        "vertical-align",
        "text-indent",
        "text-decoration",
        "text-transform",
        "text-shadow",
        "text-wrap",
        "white-space",
        "word-break",
        "word-wrap",

        "border",
        "border-block-start",
        "border-block-end",
        "border-inline-start",
        "border-inline-end",
        "border-color",
        "border-width",
        "border-radius",
        "border-style",
        "border-image",
        "outline",
        "outline-color",
        "outline-style",
        "outline-width",

        "background",
        "background-image",
        "background-color",
        "background-position",
        "background-repeat",
        "background-size",
        "background-clip",
        "background-origin",

        "box-shadow",

        "transform",
        "transform-origin",
        "transition",
        "transition-property",
        "transition-duration",
        "transition-delay",
        "transition-timing-function",

        "animation",
        "animation-name",
        "animation-duration",
        "animation-delay",
        "animation-iteration-count",
        "animation-timing-function",
      ],
      {
        unspecified: "bottomAlphabetical",
      },
    ],
    "property-disallowed-list": [
      "top",
      "left",
      "right",
      "bottom",

      "margin-top",
      "margin-right",
      "margin-bottom",
      "margin-left",
      "padding-top",
      "padding-right",
      "padding-bottom",
      "padding-left",

      "height",
      "min-height",
      "max-height",

      "width",
      "min-width",
      "max-width",

      "border-top",
      "border-right",
      "border-bottom",
      "border-left",
    ],
    "unit-allowed-list": ["%", "ms", "px", "s", "turn"],
    // 관련된 같은 속성 재정의 시 막는 규칙
    "declaration-block-no-shorthand-property-overrides": null,
    // 빈 소스를 허용하지 않는 규칙
    "no-empty-source": null,
    // 미지정된 의사 클래스를 사용할 수 없도록 제한하는 규칙
    "selector-pseudo-class-no-unknown": null,
    // 같은 클래스 선택자가 뒤에 오는 것을 허용하지 않는 규칙
    "no-descending-specificity": null,
    // rgb 콤마 허용하지 않는 규칙
    "color-function-notation": null,
    // url에 항상 따옴표 강제
    "function-url-quotes": "always",
    "no-duplicate-selectors": null,
  },
  overrides: [
    {
      files: ["packages/tailwind/**/*.css"],
      rules: {
        "at-rule-no-unknown": [true, { ignoreAtRules: ["source", "theme"] }],
        "custom-property-pattern": null,
        "scss/at-rule-no-unknown": [true, { ignoreAtRules: ["source", "theme"] }],
      },
    },
  ],
};

export default config;
