export const componentDocs = {
  accordion:
    '목적: 연관된 보조 정보를 필요할 때 펼쳐 보입니다.\n\n사용: FAQ, 설정 안내처럼 독립적인 여러 섹션을 접고 펼칠 때 사용합니다.\n\n사용하지 않음: 동등한 콘텐츠를 한 번에 하나씩 전환할 때는 Tabs를 사용합니다.\n\n기본 사용: `<Accordion.Root type="single"><Accordion.Item value="usage"><Accordion.Header><Accordion.Trigger>질문</Accordion.Trigger></Accordion.Header><Accordion.Content>답변</Accordion.Content></Accordion.Item></Accordion.Root>`\n\n주요 API: `Root`, `Item`, `Header`, `Trigger`, `Content`, `type`, `value`, `defaultValue`, `onValueChange`.\n\n접근성: Header는 h3, Trigger는 button으로 렌더링합니다. Arrow key로 Trigger 사이를 이동하며 상태와 Content 관계는 Radix가 관리합니다.\n\n커스터마이징: `--dds-accordion-border`, `--dds-accordion-trigger-hover-bg`, `--dds-accordion-trigger-open-bg` 토큰을 override합니다.',
  badge:
    '목적: 짧은 상태나 분류를 표시합니다.\n\n사용: 상태가 한눈에 구분되어야 하는 목록과 카드에 사용합니다.\n\n사용하지 않음: 색상만으로 의미를 전달해야 하는 경우에는 텍스트를 함께 제공합니다.\n\n기본 사용: `<Badge tone="success">완료</Badge>`\n\n주요 props: `variant`, `tone`, `size`, `dot`.\n\n접근성: dot은 장식이므로 보조기술에 노출되지 않습니다.\n\n커스터마이징: `--dds-color-status-*`, `--dds-radius-full` 토큰을 override합니다.',
  button:
    "목적: 사용자의 명시적 action을 실행합니다.\n\n사용: 저장, 삭제, 확인처럼 현재 화면의 동작을 실행할 때 사용합니다.\n\n사용하지 않음: 페이지 이동만 하는 경우에는 링크 semantics를 사용합니다.\n\n기본 사용: `<Button>저장</Button>`\n\n주요 props: `variant`, `tone`, `size`, `loading`, `fullWidth`.\n\n접근성: loading 중에는 native disabled와 `aria-busy`가 적용됩니다. 아이콘은 장식 처리됩니다.\n\n커스터마이징: `--dds-button-*`, `--dds-control-*` 토큰을 override합니다.",
  card: "목적: 관련된 정보를 표면 위에 그룹화합니다.\n\n사용: 제목, 설명, 본문, action 영역이 있는 독립된 정보 묶음에 사용합니다.\n\n사용하지 않음: product-specific layout이나 클릭 가능한 card를 전용 prop으로 만들지 않습니다.\n\n기본 사용: `<Card.Root><Card.Content>내용</Card.Content></Card.Root>`\n\n주요 API: `Root`, `Header`, `Title`, `Description`, `Content`, `Footer`.\n\n접근성: heading hierarchy가 필요하면 `Card.Title asChild`로 실제 heading을 전달합니다.\n\n커스터마이징: `--dds-color-bg-surface`, `--dds-color-border-default`, `--dds-shadow-sm` 토큰을 override합니다.",
  checkbox:
    '목적: 독립적인 true/false 또는 indeterminate 선택을 제공합니다.\n\n사용: 약관 동의, 설정 선택처럼 여러 값을 독립적으로 선택할 때 사용합니다.\n\n사용하지 않음: 여러 항목 중 하나만 선택하는 경우에는 RadioGroup을 사용합니다.\n\n기본 사용: `<Checkbox aria-label="알림 받기" />`\n\n주요 props: `checked`, `defaultChecked`, `onCheckedChange`, `name`, `value`.\n\n접근성: 외부 `<label htmlFor>` 또는 `aria-label`을 제공합니다. Space 키로 토글되며 checked indicator는 primary foreground 대비를 유지합니다.\n\n커스터마이징: `--dds-input-*`, `--dds-checkbox-indicator`, `--dds-focus-ring-*` 토큰을 override합니다.',
  dialog:
    "목적: 현재 작업을 중단하고 확인이나 추가 입력이 필요한 modal dialog를 제공합니다.\n\n사용: 삭제 확인처럼 즉시 주의가 필요한 흐름에 사용합니다.\n\n사용하지 않음: 단순한 보조 설명에는 Tooltip을 사용합니다.\n\n기본 사용: `<Dialog.Root><Dialog.Trigger>열기</Dialog.Trigger><Dialog.Content>...</Dialog.Content></Dialog.Root>`\n\n주요 API: `Root`, `Trigger`, `Portal`, `Content`, `Close`.\n\n접근성: Title과 Description을 제공하고 Escape, focus trap, trigger focus 복귀를 유지합니다.\n\n커스터마이징: `--dds-dialog-*`, `--dds-z-index-modal` 토큰을 override합니다.",
  dropdownMenu:
    "목적: trigger에 연결된 action menu를 제공합니다.\n\n사용: 관련된 여러 action을 compact하게 묶을 때 사용합니다.\n\n사용하지 않음: form value를 직접 선택하는 Select 용도로 사용하지 않습니다.\n\n기본 사용: `<DropdownMenu.Root><DropdownMenu.Trigger>메뉴</DropdownMenu.Trigger><DropdownMenu.Content>...</DropdownMenu.Content></DropdownMenu.Root>`\n\n주요 API: `Item`, `CheckboxItem`, `RadioGroup`, `Sub`, `SubTrigger`.\n\n접근성: keyboard navigation, Escape, disabled item, focus restore를 Radix 계약으로 제공합니다.\n\n커스터마이징: `--dds-z-index-dropdown`, `--dds-color-bg-surface-elevated` 토큰을 override합니다.",
  field:
    '목적: label, control, 설명, 오류 메시지를 일관된 form field로 구성합니다.\n\n사용: Input이나 Textarea에 visible label과 보조 메시지를 연결할 때 사용합니다.\n\n사용하지 않음: control 없이 일반 텍스트를 배치하는 layout container로 사용하지 않습니다.\n\n기본 사용: `<Field.Root><Field.Label htmlFor="email">이메일</Field.Label><Input id="email" /></Field.Root>`\n\n주요 API: `Root`, `Label`, `Description`, `Error`; Root의 `invalid`, `disabled`.\n\n접근성: native `htmlFor`/`id`와 `aria-describedby`를 명시적으로 연결하고, Root 상태와 실제 control 상태를 함께 전달합니다.\n\n커스터마이징: `--dds-color-text-*`, `--dds-color-status-danger-text`, `--dds-space-*` 토큰을 override합니다.',
  iconButton:
    '목적: 아이콘만으로 표현되는 compact action을 제공합니다.\n\n사용: 툴바처럼 공간이 제한되고 action이 명확한 곳에 사용합니다.\n\n사용하지 않음: 텍스트가 필요한 action에는 Button을 사용합니다.\n\n기본 사용: `<IconButton aria-label="닫기" icon={<CloseIcon />} />`\n\n주요 props: `aria-label`, `icon`, `variant`, `tone`, `size`, `loading`.\n\n접근성: `aria-label`은 필수이며 icon은 장식으로 처리됩니다.\n\n커스터마이징: `--dds-button-*`, `--dds-control-height-*` 토큰을 override합니다.',
  input:
    '목적: 한 줄의 native text input을 제공합니다.\n\n사용: 이름, 이메일, 검색어처럼 짧은 값을 입력할 때 사용합니다.\n\n사용하지 않음: 여러 줄 설명에는 Textarea를 사용합니다.\n\n기본 사용: `<Input id="email" />`\n\n주요 props: `size`, `invalid`와 모든 native input props.\n\n접근성: `<label htmlFor>` 또는 `aria-label`을 제공합니다. invalid 상태에는 `aria-invalid`가 적용됩니다.\n\n커스터마이징: `--dds-input-*`, `--dds-control-height-*` 토큰을 override합니다.',
  pageHeader:
    "목적: 페이지의 제목, 설명, 주요 action을 일관된 semantic header로 구성합니다.\n\n사용: 화면 최상단에서 현재 페이지의 목적과 대표 action을 함께 제시할 때 사용합니다.\n\n사용하지 않음: Card 내부의 작은 구역 제목이나 사이트 전역 navigation header에는 사용하지 않습니다.\n\n기본 사용: `<PageHeader.Root><PageHeader.Content><PageHeader.Title>프로젝트</PageHeader.Title></PageHeader.Content></PageHeader.Root>`\n\n주요 API: `Root`, `Content`, `Title`, `Description`, `Actions`.\n\n접근성: Root는 `header`, Title은 `h1`을 렌더링합니다. 페이지마다 명확한 주 제목 하나를 유지합니다.\n\n커스터마이징: `--dds-color-text-*`, `--dds-font-*`, `--dds-space-*` 토큰을 override합니다.",
  popover:
    '목적: Trigger 또는 Anchor 가까이에 추가 설정과 보조 action을 표시합니다.\n\n사용: 공유 옵션, 간단한 preview처럼 현재 맥락을 벗어나지 않는 보조 콘텐츠에 사용합니다.\n\n사용하지 않음: 사용자의 작업을 중단하거나 focus trap이 필요한 경우에는 Dialog를, 짧은 hover 도움말에는 Tooltip을 사용합니다.\n\n기본 사용: `<Popover.Root><Popover.Trigger>옵션</Popover.Trigger><Popover.Content aria-label="옵션">내용</Popover.Content></Popover.Root>`\n\n주요 API: `Root`, `Anchor`, `Trigger`, `Portal`, `Content`, `Close`, `Arrow`, `open`, `defaultOpen`, `onOpenChange`.\n\n접근성: Content는 dialog role을 사용하므로 `aria-label` 또는 `aria-labelledby`로 이름을 제공합니다. Escape와 Close로 닫을 수 있고 Trigger focus를 복귀합니다.\n\n커스터마이징: `--dds-popover-bg`, `--dds-popover-border`, `--dds-popover-radius`, `--dds-popover-shadow` 토큰을 override합니다.',
  radioGroup:
    '목적: 여러 항목 중 하나의 값을 선택합니다.\n\n사용: 공개 범위, 정렬 방식처럼 상호 배타적인 선택지에 사용합니다.\n\n사용하지 않음: 여러 값을 독립적으로 선택할 때는 Checkbox를, 즉시 적용되는 boolean 설정에는 Switch를 사용합니다.\n\n기본 사용: `<RadioGroup.Root aria-label="공개 범위"><RadioGroup.Item value="team" /></RadioGroup.Root>`\n\n주요 API: `Root`, `Item`, `value`, `defaultValue`, `onValueChange`, `name`.\n\n접근성: Root에 `aria-label` 또는 `aria-labelledby`를 제공하고, 각 Item에는 외부 `<label htmlFor>`를 연결합니다. Arrow 키로 항목 사이를 이동합니다.\n\n커스터마이징: `--dds-input-*`, `--dds-radio-indicator`, `--dds-focus-ring-*` 토큰을 override합니다.',
  spinner:
    '목적: 처리 중인 상태를 짧게 알립니다.\n\n사용: button loading이나 독립적인 비동기 처리 진행 상태에 사용합니다.\n\n사용하지 않음: 페이지의 구조가 아직 준비되지 않은 상태에는 Skeleton을 고려합니다.\n\n기본 사용: `<Spinner label="불러오는 중" />`\n\n주요 props: `size`, `label`, `decorative`.\n\n접근성: standalone은 status role과 label을 제공하고, 장식 용도에서는 `decorative`를 사용합니다.\n\n커스터마이징: `--dds-duration-slow`, `--dds-radius-full` 토큰을 override합니다.',
  switch:
    '목적: 즉시 적용되는 boolean 설정을 켜거나 끕니다.\n\n사용: 알림, 자동 저장처럼 변경 즉시 효력이 생기는 설정에 사용합니다.\n\n사용하지 않음: form 제출 전까지 확정되지 않는 선택이나 약관 동의에는 Checkbox를 사용합니다.\n\n기본 사용: `<Switch aria-label="프로젝트 알림" />`\n\n주요 props: `checked`, `defaultChecked`, `onCheckedChange`, `disabled`, `name`, `value`.\n\n접근성: 외부 `<label htmlFor>` 또는 `aria-label`을 제공하며 Space 키로 전환합니다.\n\n커스터마이징: `--dds-color-action-*`, `--dds-switch-thumb-bg`, `--dds-control-height-*`, `--dds-duration-fast` 토큰을 override합니다.',
  tabs: '목적: 같은 맥락의 콘텐츠 영역을 한 번에 하나씩 전환합니다.\n\n사용: 프로젝트 설정, 상세 정보처럼 동등한 섹션을 좁은 공간에서 전환할 때 사용합니다.\n\n사용하지 않음: 순차적인 단계 진행에는 전용 stepper를, 독립적으로 여러 영역을 펼치는 경우에는 Accordion을 사용합니다.\n\n기본 사용: `<Tabs.Root defaultValue="overview"><Tabs.List aria-label="프로젝트 설정"><Tabs.Trigger value="overview">개요</Tabs.Trigger></Tabs.List><Tabs.Content value="overview">내용</Tabs.Content></Tabs.Root>`\n\n주요 API: `Root`, `List`, `Trigger`, `Content`, `value`, `defaultValue`, `onValueChange`.\n\n접근성: List에 접근 가능한 이름을 제공하고, Arrow key로 tab 사이를 이동합니다. Trigger와 Content의 role 및 관계는 Radix가 연결합니다.\n\n커스터마이징: `--dds-tabs-border`, `--dds-tabs-active-border`, `--dds-tabs-active-text` 토큰을 override합니다.',
  toast:
    '목적: 저장 완료처럼 짧게 확인할 수 있는 일시적 피드백을 제공합니다.\n\n사용: 사용자의 action이 성공했거나 상태가 바뀌었음을 현재 흐름을 방해하지 않고 알릴 때 사용합니다.\n\n사용하지 않음: 사용자의 확인이 필요한 위험한 작업에는 Dialog를, 화면 안에서 계속 보여야 하는 상태에는 Badge나 inline message를 사용합니다.\n\n기본 사용: `<Toast.Provider><Toast.Root defaultOpen type="background"><Toast.Title>저장 완료</Toast.Title><Toast.Description>변경사항을 저장했습니다.</Toast.Description><Toast.Close aria-label="알림 닫기">닫기</Toast.Close></Toast.Root><Toast.Viewport label="알림 ({hotkey})" /></Toast.Provider>`\n\n주요 API: `Provider`, `Viewport`, `Root`, `Title`, `Description`, `Action`, `Close`, `tone`, `open`, `defaultOpen`, `onOpenChange`.\n\n접근성: 비긴급 알림은 `type="background"`로 polite announcement를 사용합니다. Action에는 screen reader용 대체 동작 설명인 `altText`가 필수이며 Viewport는 localised label과 F8 shortcut을 제공합니다.\n\n커스터마이징: `--dds-toast-bg`, `--dds-toast-text`, `--dds-toast-border`, `--dds-toast-*-accent` 토큰을 override합니다.',
  textarea:
    '목적: 여러 줄의 native text input을 제공합니다.\n\n사용: 설명, 의견, 메시지처럼 긴 값을 입력할 때 사용합니다.\n\n사용하지 않음: 짧은 한 줄 값에는 Input을 사용합니다.\n\n기본 사용: `<Textarea id="description" />`\n\n주요 props: `size`, `invalid`, `resize`와 모든 native textarea props.\n\n접근성: `<label htmlFor>` 또는 `aria-label`을 제공하고 invalid 상태를 명시합니다.\n\n커스터마이징: `--dds-input-*`, `--dds-space-*` 토큰을 override합니다.',
  tooltip:
    "목적: hover 또는 keyboard focus로 보조 설명을 제공합니다.\n\n사용: 아이콘 의미나 짧은 추가 맥락을 제공할 때 사용합니다.\n\n사용하지 않음: 필수 정보나 오류 메시지의 유일한 전달 수단으로 사용하지 않습니다.\n\n기본 사용: `<Tooltip.Root><Tooltip.Trigger>도움말</Tooltip.Trigger><Tooltip.Content>설명</Tooltip.Content></Tooltip.Root>`\n\n주요 API: `Provider`, `Root`, `Trigger`, `Content`, `Arrow`.\n\n접근성: trigger와 tooltip role의 관계가 연결되며 focus와 hover 모두 지원합니다.\n\n커스터마이징: `--dds-tooltip-*`, `--dds-z-index-tooltip` 토큰을 override합니다.",
} as const;
